package common;

public enum MessageType {
    LOGIN, LOGIN_OK, LOGIN_FAIL,
    ONLINE_LIST,
    INVITE, INVITE_RESPONSE,
    CREATE_ROOM, JOIN_ROOM, ROOM_UPDATE,
    START_GAME, DEAL_CARDS, DRAW_CARD,
    GAME_RESULT, PLAY_AGAIN, LEAVE,
    PING, PONG, INFO
}
